# Generated by Django 5.0.4 on 2024-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('P', 'Pessoal'), ('PR', 'Profissional'), ('A', 'Acadêmico')], max_length=2)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
